/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package synergy.api;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.net.URL;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

class LibraryTest {
	
	public LibraryTest() {
		
	}
		
	@Test 
	public void componentTest() {
		Integer id = 1;
		String name = "My component";
		String description = "Component description";
		
		Component component = new Component (id, name, description);
		assertEquals(component.getId(), id);
		assertEquals(component.getName(), name);
		assertEquals(component.getDescription(), description);
	}
		
	@Test
	public void processTest() {
		Integer id = 1;
		String name = "My process";
		String description = "This is a test Process";
		
		Process process = new Process(id, name, description);
		/*
		List<Field> arrayOfFields = Arrays.asList(textField, dateField, attachmentField, numberField);
		for (Field field : arrayOfFields) {
			process.getFields().add(field);
		}
		*/
		assertEquals(process.getId(), id);
		assertEquals(process.getName(), name);
		assertEquals(process.getDescription(), description);
		//assertIterableEquals(process.getFields(), arrayOfFields);
	}
}
